# Generated by Django 4.0.3 on 2022-03-30 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Client'), ('trainer', 'Trainer')], max_length=7)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FavouriteTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to=settings.AUTH_USER_MODEL)),
                ('trainer_id', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite_trainers',
                'unique_together': {('client_id', 'trainer_id')},
            },
        ),
    ]
