# Generated by Django 4.0.3 on 2022-03-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo_path',
            field=models.FileField(upload_to=''),
        ),
    ]
