# Generated by Django 4.0.3 on 2022-03-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_remove_meal_photo_path_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='image',
            new_name='photo_path',
        ),
    ]
